### ISSUE TITLE
Remove weird button near topic titles

### ISSUE THREAD

**Issue by buildthomas** [roblox-dev-forum/discourse-question-answer#4]
We don't need this button, looks weird

**Comment by Kampfkarren** [comment]
Screenshot?

**Comment by buildthomas** [comment]
See example at https://discourse.angusmcleod.com.au/t/what-has-cities-but-no-houses-forests-but-no-trees-and-water-but-no-fish/55

**Comment by Kampfkarren** [comment]
Looks to be gone since the last time I checked.
![image](https://user-images.githubusercontent.com/3190756/73135046-bfc1b500-3ff2-11ea-9a25-04e9239ffd56.png)

**Comment by Kampfkarren** [comment]
There is a setting already built in to turn it off.

https://github.com/paviliondev/discourse-question-answer/blob/ae8d2e1ef65f1313e0e4ee9eef5cf4c4dc774635/assets/javascripts/discourse/initializers/qa-edits.js.es6#L385
